[build]
command = "hugo -b https://docs.zen-cart.com"
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.103.0"
HUGO_ENV = "production"

[[redirects]]
  from = "https://zencartdocs.netlify.com/*"
  to = "https://docs.zen-cart.com/:splat"
  status = 301
  force = true
